version: '3.9'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: [ "sh", "/entrypoint.sh" ]
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-server
    ports:
      - "8080:8080"
    depends_on:
      - ollama
    volumes:
      - .:/app
    command: sh -c "chmod +x startup.sh && ./startup.sh && uvicorn main:app --host 0.0.0.0 --port 8080"

networks:
  app-network:
